- name: Remove Instances
  ec2:
    state: absent
    instance_ids: "{{hostvars[item].instance_id}}"
    region: "{{ region }}"
  with_items: "{{ groups['VMS'] }}"
  when: groups['VMS'] | length > 0

- name: Remove registry from inventory
  lineinfile:
    path: "{{ playbook_dir }}/environment/hosts"
    regexp: "^{{item}}"
    state: absent
  with_items: "{{ groups['VMS'] }}"
  when: groups['VMS'] | length > 0

- debug:
    msg: "Check the inventory file environments/hosts to make sure hosts are removed"

- name: Check dockerreg record
  route53_info:
    type: A
    query: record_sets
    hosted_zone_id: "{{ dnszoneid }}"
    start_record_name: "dockerreg.{{dnszone}}"
  register: dockerreg

- name: Remove Dockerreg DNS entries
  route53:
    state: absent
    zone: "{{ dnszone }}"
    record: "dockerreg.{{ dnszone }}"
    type: A
    ttl: 60
    value:
      - "{{ groups['VMS'][0] }}"
  when: dockerreg is defined
